FdfEksamen2/Controllers/BetalingsController.cs
using FDFVANLØSEEKSAMEN.Repository.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FDFVANLØSEEKSAMEN.Controllers
{
    public class BetalingsController : Controller
    {
        private readonly easylotterik19_dk_db_fdfContext _context;

        public BetalingsController(easylotterik19_dk_db_fdfContext context)
        {
            _context = context;
        }

        // GET: Betalinger
        public async Task<IActionResult> Index()
        {
            var easylotterik19_dk_db_fdfContext = _context.Betalings.Include(p => p.Barn);
            return View(await easylotterik19_dk_db_fdfContext.ToListAsync());
        }

        // GET: Betalinger/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Betalings == null)
            {
                return NotFound();
            }

            var betaling = await _context.Betalings
                .Include(p => p.Barn )
                .FirstOrDefaultAsync(m => m.BetalingsId == id);
            if (betaling == null)
            {
                return NotFound();
            }

            return View(betaling);
        }

        // GET: Betalinger/Create
        public IActionResult Create()
        {
            ViewData["BarnId"] = new SelectList(_context.Barns, "BarnId", "Bnavn");
            return View();
        }

        // POST: Betalinger/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BetalingsId,BetalingsDato,Beløbet,AntalLod,BarnId")] Betaling betaling)
        {
            if (ModelState.IsValid)
            {
                _context.Add(betaling);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BarnId"] = new SelectList(_context.Barns, "BarnId", "Bnavn", betaling.BarnId);
            return View(betaling);
        }

        // GET: Betalinger/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Betalings == null)
            {
                return NotFound();
            }

            var betaling = await _context.Betalings.FindAsync(id);
            if (betaling == null)
            {
                return NotFound();
            }
            ViewData["BarnId"] = new SelectList(_context.Barns, "BarnId", "Bnavn", betaling.BarnId);
            return View(betaling);
        }

        // POST: Betalinger/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BetalingsId,BetalingsDato,Beløbet,AntalLod,BarnId")] Betaling betaling)
        {
            if (id != betaling.BetalingsId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(betaling);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BetalingExists(betaling.BetalingsId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BarnId"] = new SelectList(_context.Barns, "BarnId", "Bnavn", betaling.BarnId);
            return View(betaling);
        }

        // GET: Betalinger/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Betalings == null)
            {
                return NotFound();
            }

            var betaling = await _context.Betalings
                .Include(p => p.Barn)
                .FirstOrDefaultAsync(m => m.BetalingsId == id);
            if (betaling == null)
            {
                return NotFound();
            }

            return View(betaling);
        }

        // POST: Betalinger/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Betalings == null)
            {
                return Problem("Entity set 'easylotterik19_dk_db_fdfContext.Betaling'  is null.");
            }
            var betaling = await _context.Betalings.FindAsync(id);
            if (betaling != null)
            {
                _context.Betalings.Remove(betaling);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BetalingExists(int id)
        {
            return (_context.Betalings?.Any(e => e.BetalingsId == id)).GetValueOrDefault();
        }
    }
}

FdfEksamen2/Controllers/BørneController.cs
using FDFVANLØSEEKSAMEN.Repository.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FDFVANLØSEEKSAMEN.Controllers
{
    public class BørneController : Controller
  { 
    private readonly easylotterik19_dk_db_fdfContext _context;

    public BørneController(easylotterik19_dk_db_fdfContext context)
    {
        _context = context;
    }

    // GET: Børn
    public async Task<IActionResult> Index()
    {
        var easylotterik19_dk_db_fdfContext = _context.Barns.Include(c => c.Bg);
        return View(await easylotterik19_dk_db_fdfContext.ToListAsync());
    }

        // GET: Børn/Details/5
        public async Task<IActionResult> Details(int? id)
    {
        if (id == null || _context.Barns == null)
        {
            return NotFound();
        }

        var barn = await _context.Barns
            .Include(c => c.Bg)
            .FirstOrDefaultAsync(m => m.BarnId == id);
        if (barn == null)
        {
            return NotFound();
        }

        return View(barn);
    }

        // GET: Børn/Create
        public IActionResult Create()
    {
        ViewData["Bgid"] = new SelectList(_context.BørneGruppes, "Bgid", "Bgnavn");
        return View();
    }

        // POST: Børn/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("BarnId,Bnavn,Bgid,ModtagetLod,RetuneretLod")] Barn barn)
    {
        if (ModelState.IsValid)
        {
            _context.Add(barn);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        ViewData["Bgid"] = new SelectList(_context.BørneGruppes, "Bgid", "Bgnavn", barn.BarnId);
        return View(barn);
    }

        // GET: Børn/Edit/5
        public async Task<IActionResult> Edit(int? id)
    {
        if (id == null || _context.Barns == null)
        {
            return NotFound();
        }

        var barn = await _context.Barns.FindAsync(id);
        if (barn == null)
        {
            return NotFound();
        }
        ViewData["Bgid"] = new SelectList(_context.BørneGruppes, "Bgid", "Bgnavn", barn.Bgid);
        return View(barn);
    }

        // POST: Børn/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("BarnId,Bnavn,Bgid,ModtagetLod,RetuneretLod")] Barn barn)
        {
        if (id != barn.BarnId)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(barn);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BarnExsist(barn.BarnId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        ViewData["Bgid"] = new SelectList(_context.BørneGruppes, "Bgid", "Bgnavn", barn.BarnId);
        return View(barn);
    }

        // GET: Børn/Delete/5
        public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || _context.Barns == null)
        {
            return NotFound();
        }

        var barn = await _context.Barns
            .Include(c => c.Bg)
            .FirstOrDefaultAsync(m => m.BarnId == id);
        if (barn == null)
        {
            return NotFound();
        }

        return View(barn);
    }

        // POST: Børn/Delete/5
        [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        if (_context.Barns == null)
        {
            return Problem("Entity set 'easylotterik19_dk_db_fdfContext.Børn'  is null.");
        }
        var barn = await _context.Barns.FindAsync(id);
        if (barn != null)
        {
            _context.Barns.Remove(barn);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool BarnExsist(int id)
    {
        return (_context.Barns?.Any(e => e.BarnId == id)).GetValueOrDefault();
    }
}
}

FdfEksamen2/Controllers/BørneGruppeController.cs
using FDFVANLØSEEKSAMEN.Repository.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FDFVANLØSEEKSAMEN.Controllers
{
    public class BørneGruppeController : Controller
    {
            private readonly easylotterik19_dk_db_fdfContext _context;

            public BørneGruppeController(easylotterik19_dk_db_fdfContext context)
            {
                _context = context;
            }

        // GET: Børnegrupper
        public async Task<IActionResult> Index()
            {
                var easylotterik19_dk_db_fdfContext = _context.BørneGruppes.Include(c => c.Leder);
                return View(await easylotterik19_dk_db_fdfContext.ToListAsync());
            }

        // GET: Børnegrupper/Details/5
        public async Task<IActionResult> Details(int? id)
            {
                if (id == null || _context.BørneGruppes == null)
                {
                    return NotFound();
                }

                var childGroup = await _context.BørneGruppes
                    .Include(c => c.Leder)
                    .FirstOrDefaultAsync(m => m.Bgid == id);
                if (childGroup == null)
                {
                    return NotFound();
                }

                return View(childGroup);
            }

        // GET: Børnegrupper/Create
        public IActionResult Create()
            {
                var list = new List<SelectListItem>();
                var userList = _context.Brugers.Where(x => x.Rolle == "Leder").ToList();
                foreach (var user in userList)
                {
                    list.Add(new SelectListItem { Value = user.BrugerId.ToString(), Text = user.Brugernavn });
                }
            //ViewData["LederId"] = new SelectList(_context.Users, "BrugerID", "BrugerID");
            ViewBag.LederId = list;
                return View();
            }

        // POST: Børnegrupper/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Create([Bind("BGID,BGNavn,LederID,ModtagetLod,RetuneretLod")] BørneGruppe børneGruppe)
            {
                if (ModelState.IsValid)
                {
                    _context.Add(børneGruppe);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewData["LederID"] = new SelectList(_context.Brugers.Where(x => x.Rolle == "Leder"), "BrugerID", "Brugernavn", børneGruppe.LederId);
                return View(børneGruppe);
            }

        // GET: Børnegrupper/Edit/5
        public async Task<IActionResult> Edit(int? id)
            {
                if (id == null || _context.BørneGruppes == null)
                {
                    return NotFound();
                }

                var børneGruppe = await _context.BørneGruppes.FindAsync(id);
                if (børneGruppe == null)
                {
                    return NotFound();
                }
                ViewData["LeaderId"] = new SelectList(_context.Brugers.Where(x => x.Rolle == "Leder"), "BrugerID", "Brugernavn", børneGruppe.LederId);
                return View(børneGruppe);
            }

        // POST: Børnegrupper/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Edit(int id, [Bind("BGID,BGNavn,LederID,ModtagetLod,RetuneretLOD")] BørneGruppe børneGruppe)
            {
                if (id != børneGruppe.Bgid)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(børneGruppe);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!BørneGruppeExists(børneGruppe.Bgid))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                ViewData["LederId"] = new SelectList(_context.Brugers, "BrugerID", "Brugernavn", børneGruppe.LederId);
                return View(børneGruppe);
            }

        // GET: Børnegrupper/Delete/5
        public async Task<IActionResult> Delete(int? id)
            {
                if (id == null || _context.BørneGruppes == null)
                {
                    return NotFound();
                }

                var børneGruppe = await _context.BørneGruppes
                    .Include(c => c.Leder)
                    .FirstOrDefaultAsync(m => m.Bgid == id);
                if (børneGruppe == null)
                {
                    return NotFound();
                }

                return View(børneGruppe);
            }

        // POST: Børnegrupper/Delete/5
        [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> DeleteConfirmed(int id)
            {
                if (_context.BørneGruppes == null)
                {
                    return Problem("Entity set 'easylotterik19_dk_db_fdfContext.Børnegrupper'  is null.");
                }
                var børneGruppe = await _context.BørneGruppes.FindAsync(id);
                if (børneGruppe != null)
                {
                    _context.BørneGruppes.Remove(børneGruppe);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            private bool BørneGruppeExists(int id)
            {
                return (_context.BørneGruppes?.Any(e => e.Bgid == id)).GetValueOrDefault();
            }
        }
    }

FdfEksamen2/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FDFVANLØSEEKSAMEN</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FDFVANLØSEEKSAMEN.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FDFVANLØSEEKSAMEN</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FDFVANLØSEEKSAMEN - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FdfEksamen2/Pages/Shared/_LayoutBestyrelse.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LotteriBestyrer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="">Bestyrelsen</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LotteriBestyrer - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FdfEksamen2/Pages/Shared/_LayoutLotteriBestyrer.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LotteriBestyrer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="">Lotteri Bestyrer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BørneGruppe" asp-action="Index">BørneGrupper</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Børne" asp-action="Index">Børn</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Betalings" asp-action="Index">Betalinger</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LotteriBestyrer - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FdfEksamen2/Pages/Shared/_Layoutleder.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LotteriBestyrer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="">Leder</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LotteriBestyrer - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>